#server:
#  port: 9999

spring:
#  rabbitmq:
#    port: 5672
#    username: call_center
#    password: i4vtMx9nLEzv6ZhiUg2gXofo
#    host: 95.216.166.202
#    virtualHost: call_center

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sbank
    username: postgres
    password: qwe321

  jpa:
    hibernate:
      ddl-auto: create-drop #update

